#!/usr/bin/env python3
"""
gather_files.py
# gather_files.py
# Path: ./gather_files.py

Recursively find files in subfolders and concatenate them into a single combined file.
Configuration is easy via the top-level variables:

- DEFAULT_SKIP_DIRS: directories to skip by default
- WHITELIST_EXTENSIONS: set of file extensions to include (with or without leading dot), e.g. {".py","js","html"}
- WHITELIST_PATHS: set of relative paths (from source_root) to include exactly

Behavior:
- A file is included if its extension is in WHITELIST_EXTENSIONS OR its relative path is in WHITELIST_PATHS.
- If WHITELIST_EXTENSIONS is empty and WHITELIST_PATHS empty, no files will be selected.
- You can still exclude files by basename using --exclude-files, and exclude dirs via --exclude-dirs.
"""

import os
import sys
import io
import argparse

# === CONFIGURE HERE ===
# Default directories to skip
DEFAULT_SKIP_DIRS = {
    "__pycache__", "venv", "tools", "data", "images","combined.py", "3network_live_demo.html", "snetwork_live_demo", ".txt", ".bak", "gather_py_files","addDebugPrintStatements", "3network_live_demo", ".venv", "env", ".env", "build", "dist", ".git", ".hg", ".mypy_cache"
}

# Allowed file extensions to gather (can include leading dot or not). Edit to include ".py", "js", "html", etc.
WHITELIST_EXTENSIONS = {".py", ".js", ".css", ".html"}  # example: {".py", "js", "html"}

# Specific relative paths (from source_root) to include regardless of extension.
# Example: {"src/index.html", "scripts/app.js"}
WHITELIST_PATHS = set()
# =======================

def load_list_file(path, relative=False):
    try:
        with io.open(path, "r", encoding="utf-8") as f:
            items = [line.strip() for line in f if line.strip() and not line.strip().startswith("#")]
            if relative:
                return {os.path.normpath(item) for item in items}
            return {item for item in items}
    except Exception:
        return set()

def normalize_extensions(exts):
    out = set()
    for e in exts:
        if not e:
            continue
        s = str(e).strip().lower()
        if s.startswith("."):
            s = s[1:]
        out.add(s)
    return out

def should_include_file(fullpath, root, whitelist_exts, whitelist_paths, exclude_basenames):
    rel = os.path.relpath(fullpath, root)
    norm_rel = os.path.normpath(rel)
    base = os.path.basename(fullpath)
    if base in exclude_basenames:
        return False
    # exact path whitelist
    if norm_rel in whitelist_paths:
        return True
    # extension whitelist
    _, ext = os.path.splitext(fullpath)
    if ext.startswith("."):
        ext = ext[1:].lower()
    else:
        ext = ""
    if ext and ext in whitelist_exts:
        return True
    return False

def gather_files(root, skip_dirs, whitelist_exts, whitelist_paths, exclude_files):
    files = []
    root = os.path.abspath(root)
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in skip_dirs and not d.startswith(".")]
        for fn in filenames:
            full = os.path.join(dirpath, fn)
            # skip this script itself
            if os.path.abspath(full) == os.path.abspath(__file__):
                continue
            if should_include_file(full, root, whitelist_exts, whitelist_paths, exclude_files):
                files.append(full)
    return sorted(files)

def read_file(path):
    with io.open(path, "r", encoding="utf-8", errors="replace") as f:
        return f.read()

def write_combined(files, out_path, root):
    with io.open(out_path, "w", encoding="utf-8") as out:
        out.write("# combined file\n")
        out.write("# Generated by gather_files.py\n\n")
        for p in files:
            rel = os.path.relpath(p, root)
            out.write("\n")
            out.write("# ========================\n")
            out.write(f"# FILE: {rel}\n")
            out.write("# ========================\n\n")
            try:
                content = read_file(p)
            except Exception as e:
                content = f"# ERROR reading file: {e}\n"
            out.write(content)
            out.write("\n\n")
    print(f"Wrote combined file: {out_path}")

def main():
    parser = argparse.ArgumentParser(description="Gather whitelisted files into one combined file")
    parser.add_argument("source_root", nargs="?", default=os.getcwd(), help="Source root to scan")
    parser.add_argument("output_path", nargs="?", default=os.path.join(os.getcwd(), "combined.txt"), help="Output combined file")
    parser.add_argument("--exclude-files", help="Path to file listing basenames to exclude (one per line)")
    parser.add_argument("--exclude-dirs", help="Comma-separated additional dir names to exclude")
    args = parser.parse_args()

    root = args.source_root
    out = args.output_path

    skip_dirs = set(DEFAULT_SKIP_DIRS)
    if args.exclude_dirs:
        extra = [d.strip() for d in args.exclude_dirs.split(",") if d.strip()]
        skip_dirs.update(extra)

    exclude_files = set()
    if args.exclude_files:
        exclude_files = load_list_file(args.exclude_files)

    # normalize and use configured top-level WHITELIST_EXTENSIONS and WHITELIST_PATHS
    whitelist_exts = normalize_extensions(WHITELIST_EXTENSIONS)
    whitelist_paths = {os.path.normpath(p) for p in WHITELIST_PATHS}

    files = gather_files(root, skip_dirs, whitelist_exts, whitelist_paths, exclude_files)

    if not files:
        print("No files found with the current whitelist rules.")
        return

    write_combined(files, out, root)

if __name__ == "__main__":
    main()
